sudo: false

language: php

notifications:
    email:
        on_success: never
        on_failure: change

branches:
    only:
        - master

php:
    - 5.5

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1

before_script:
    composer install

script: composer check

after_success:
    - composer coverage-clover
    - composer require codacy/coverage
    - php vendor/bin/codacycoverage clover coverage.xml -t da3541629da0477295d149ef3628839f
