name: CI Testing

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Testing
    strategy:
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4]
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}-apache
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        mv composer.phar composer
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --ignore-platform-reqs --prefer-dist
    - name: Run tests
      run: vendor/bin/phpunit
